version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Helloworld-Stack2021"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wxx2gi4qq548"
s3_prefix = "Helloworld-Stack2021"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=247693391151.dkr.ecr.us-east-1.amazonaws.com/helloworldstack20217e672f09/helloworldfunction19d43fc4repo"]
